# Generated by Django 4.1.7 on 2023-03-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pool',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PoolChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolsapp.pool')),
            ],
        ),
    ]
