# Generated by Django 4.1.7 on 2023-04-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0002_alter_pool_is_active_alter_pool_title_poolchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='is_active',
        ),
    ]
