# Generated by Django 4.1.7 on 2023-04-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0003_remove_pool_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoolChoice',
            new_name='Questions',
        ),
    ]
