# Generated by Django 4.1.7 on 2023-04-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0004_rename_poolchoice_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poolsapp.pool'),
        ),
    ]
