# Generated by Django 4.1.7 on 2023-04-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0005_alter_questions_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='choice_text',
            new_name='question_text',
        ),
    ]
