# Generated by Django 4.1.7 on 2023-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsapp', '0006_rename_choice_text_questions_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='question',
            field=models.CharField(default='', max_length=200),
        ),
    ]
